### ISSUE TITLE
Fullscreen Shiny: Deprecated jQuery

### ISSUE THREAD

**Issue by RichardD2** [jumpingrivers/blog#19]
The the [Fullscreen Ahead for Shiny Applications](https://www.jumpingrivers.com/blog/fullscreen-r-shiny-javascript-api/) block, you include the following:

> We’ll begin by using the ready method to ensure the code inside the supplied function isn’t run until the page has loaded and our plot containers are a part of it:

```
$(document).ready(function() {
    'use strict';

    // Interesting code goes here
});
```

But as described in [the jQuery documentation](https://api.jquery.com/ready/), this approach is deprecated:

> jQuery offers several ways to attach a function that will run when the DOM is ready. All of the following syntaxes are equivalent:
> 
> * `$( handler )`
> * `$( document ).ready( handler )`
> * `$( "document" ).ready( handler )`
> * `$( "img" ).ready( handler )`
> * `$().ready( handler )`
> 
> As of jQuery 3.0, **only the first syntax is recommended**; the other syntaxes still work but are deprecated. This is because the selection has no bearing on the behavior of the .ready() method, which is inefficient and can lead to incorrect assumptions about the method's behavior. For example, the third syntax works with "document" which selects nothing. The fourth syntax waits for the document to be ready but implies (incorrectly) that it waits for images to become ready. 

Your code should therefore be:

```
$(function() {
    'use strict';

    // Interesting code goes here
});
```

**Comment by timbrock** [comment]
Ah, thanks! I will update.
